#=========================================================================
# run_test.yml
#=========================================================================
# Workflow to run PyMTL3 tests

name: Run Tests

on:
  push:
    branches: [ nbitregister ]
  pull_request:
    branches: [ nbitregister ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_cmd:
          - ../register -v --tb=short
          - ../register -v --test-verilog

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Verilator
      run: |
        wget https://github.com/cornell-brg/verilator-travisci-cache/raw/master/verilator-travis-4.036.tar.gz
        tar -C ${HOME} -xzf verilator-travis-4.036.tar.gz
        echo "VERILATOR_ROOT=${HOME}/verilator" >> $GITHUB_ENV
        echo "PYMTL_VERILATOR_INCLUDE_DIR=${HOME}/verilator/share/verilator/include" >> $GITHUB_ENV
        echo "${HOME}/verilator/bin" >> $GITHUB_PATH
    - name: Check Verilator
      run: |
        echo ${VERILATOR_ROOT}
        echo ${PYMTL_VERILATOR_INCLUDE_DIR}
        verilator --version
    - name: Install dependencies
      run: |
        sudo apt-get install -y graphviz
        pip install --upgrade pip
        pip install pymtl3
        pip install numpy
        pip install fxpmath
    - name: Run tests
      timeout-minutes: 5
      run: |
        mkdir -p nbitregister/sim/build && cd nbitregister/sim/build
        pytest ${{ matrix.test_cmd }} --verbose
